version: '3.9'

networks:
  app-network:
    driver: bridge

services:

  # ASP.NET Core Web API Application
  shop-webapi:
    image: ${DOCKER_REGISTRY-}shop-webapi
    container_name: shop-webapi
    restart: always
    build:
      context: .
      dockerfile: src/Shop.PublicApi/Dockerfile
    expose:
      - 5072
    ports:
      - 5072:5072
    links:
      - sqlserver
      - mongoserver
      - redis
    networks:
      - app-network
    depends_on:
      - sqlserver
      - mongoserver
      - redis

  # SQL Server
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    cap_add: [ 'SYS_PTRACE' ]
    hostname: mssql
    container_name: sqlserver
    restart: always
    expose:
      - 1433
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=pMA63033n6tF
    networks:
      - app-network

  # MongoDB Server
  mongoserver:
    image: mongo:latest
    container_name: mongoserver
    restart: always
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - app-network

  # Redis Cache Server
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass pMA63033n6tF
    restart: always
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - app-network
